# Use an official Python runtime as the base image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy your Python script and any other necessary files into the container
COPY numbersandwordsorter.py .

# Run the Python script when the container starts
CMD ["python", "numbersandwordsorter.py"]

